import { prisma } from "@/lib/prisma";
import { Prisma } from "@/generated/prisma/client";

export function listProjectsForUser(userId: string) {
  return prisma.project.findMany({
    where: { userId },
    orderBy: { createdAt: "desc" },
  });
}

export function getProjectBySlug(slug: string) {
  return prisma.project.findUnique({ where: { slug } });
}

/** Scoped to `userId` so callers never need a separate ownership check. */
export function getProjectForOwner(userId: string, projectId: string) {
  return prisma.project.findFirst({ where: { id: projectId, userId } });
}

// Strips combining diacritical marks left behind by NFKD normalization
// (e.g. turns "café" into "cafe" instead of dropping the whole character).
const COMBINING_MARKS = /\p{Mn}/gu;

export function slugify(input: string): string {
  const slug = input
    .toLowerCase()
    .normalize("NFKD")
    .replace(COMBINING_MARKS, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/-+$/g, "");
  return slug || "site";
}

function isUniqueSlugConflict(error: unknown): boolean {
  return (
    error instanceof Prisma.PrismaClientKnownRequestError &&
    error.code === "P2002" &&
    Array.isArray(error.meta?.target) &&
    error.meta.target.includes("slug")
  );
}

const MAX_SLUG_ATTEMPTS = 50;

/**
 * Creates the Project row with a guaranteed-unique slug, retrying with a
 * numeric suffix on collision (FR-18). `id` is generated by the caller
 * up front so the storage path can be written before this DB row exists.
 */
export async function createProjectRecord({
  id,
  userId,
  name,
  storagePath,
}: {
  id: string;
  userId: string;
  name: string;
  storagePath: string;
}) {
  const base = slugify(name);
  let candidate = base;

  for (let attempt = 1; attempt <= MAX_SLUG_ATTEMPTS; attempt++) {
    try {
      return await prisma.project.create({
        data: { id, userId, name, slug: candidate, storagePath },
      });
    } catch (error) {
      if (isUniqueSlugConflict(error) && attempt < MAX_SLUG_ATTEMPTS) {
        candidate = `${base}-${attempt + 1}`;
        continue;
      }
      throw error;
    }
  }

  throw new Error("Could not generate a unique project slug");
}
